# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'MarvelBrowser-Swift' do

pod 'Alamofire', '~> 1.2'

end

target 'MarvelBrowser-SwiftTests' do

end

